// Generated by CoffeeScript 1.10.0
var clong, countdowner, end, exercise, exercises, image, isLastIndex, setExerciseText, setImage, setTimerText, showExercise, showResting, start, timer;

exercises = ["Running in Place", "Jumping Jacks", "Jumping Squats", "Push Ups", "Bicycle Crunch", "Burpees", "Mason Twist", "Mountain Climbers"];

timer = document.getElementById("timer");

exercise = document.getElementById("exercise");

image = document.getElementById("img");

clong = new Audio("clong.mp3");

countdowner = function(time, nextFunction) {
  setTimerText(time);
  if (time === 0) {
    clong.play();
    return nextFunction();
  } else {
    return setTimeout((function() {
      return countdowner(time - 1, nextFunction);
    }), 1000);
  }
};

start = function() {
  setExerciseText("Get Ready!");
  return countdowner(3, (function() {
    return showExercise(0);
  }));
};

showExercise = function(index) {
  setExerciseText(exercises[index]);
  setImage("img/" + exercises[index] + ".png");
  return countdowner(20, (function() {
    return showResting(index);
  }));
};

showResting = function(index) {
  setImage("");
  if (isLastIndex(index)) {
    return end();
  } else {
    setExerciseText("Resting (" + exercises[index + 1] + " Next)");
    return countdowner(10, (function() {
      return showExercise(index + 1);
    }));
  }
};

end = function() {
  setTimerText("");
  return setExerciseText("All Done!");
};

setTimerText = function(text) {
  return timer.innerText = text;
};

setExerciseText = function(text) {
  return exercise.innerText = text;
};

setImage = function(img) {
  return image.src = img;
};

isLastIndex = function(index) {
  return exercises[index + 1] === void 0;
};
